### ISSUE TITLE
Output pin for PWM not being set

### ISSUE THREAD

**Issue by akepecs** [hallee/espresso-arm#1]
I'm using a RaspberryPi Zero and I was getting the following error:

remi.server      INFO     Started httpserver http://127.0.0.1:8081/
remi.server.http DEBUG    get: /
Initiated Heater PWM.
**wiringPiSetup*: You must only call this once per program run. This is a fatal error. Please fix your code.**

It seems that wp.wiringPiSetup() is being called in the the HeaterPWM.py module after its already called in the max31855.py module. As a result, the next line,  wp.pinMode(pin, 1), is never executed and the PWM pin doesn't get set to OUTPUT mode.

Removing the wiringPiSetup() line in the HeaterPWM.py module fixed the problem. 

Thanks for creating this PID Controller. It's super easy to use and is doing a great job on my Gaggia.

**Comment by hallee** [comment]
Oops! I wasn't getting that error with the Odroid modified version of WiringPi. 

Should be fixed. And it's good to hear that this works on a Zero.
